### ISSUE TITLE
Como usuario, quiero filtrar los campings de acuerdo a los criterios que más me acomoden.

### ISSUE THREAD

**Issue by MartinLFD** [joaonunez/proyecto-final-front-end-pt-50#16]
Historia de usuario:
- Como usuario, quiero filtrar los campings de acuerdo a los criterios que más me acomoden.

Criterio de aceptación:
 - Filtrado por: 
   *Servicios: Baño/ Agua caliente/ Luz eléctrica/ Estacionamiento/ Hornilla/ Mesa/ Techo/ Agua potable/ Pet Friendly/
   *Servicios Adicionales: Wifi/ Tinaja/ Baño privado/ Piscina/ Restaurante/ Mini-market/ Leña/ Carbón/ Actividades/ Cabañas/
   *Servicios Premium: Cancha de tenis/  Paddle/ Embarcadero/ Laguna de pesca/ Botes/ Servicio Guía Turístico/ otros.

**Comment by joaonunez** [comment]
Consultar algo en la base de datos, input selector con buscador, cambiar ultimo criterio

**Comment by MartinLFD** [comment]
Cambios realizados.

**Comment by MartinLFD** [comment]
Servicio "Pet Friendly" agregado.
