### ISSUE TITLE
Como usuario, quiero filtrar búsqueda por región y lugar.

### ISSUE THREAD

**Issue by MartinLFD** [joaonunez/proyecto-final-front-end-pt-50#19]
Historia de usuario:
- Como usuario, quiero filtrar búsqueda por región y lugar.

Criterio de aceptación:
- Acceso a la Funcionalidad de Búsqueda, Filtro de región y lugar disponibles.

**Comment by joaonunez** [comment]
Generalizar esta historia, y sus criterios

**Comment by MartinLFD** [comment]
Cambios realizados.
