### ISSUE TITLE
Como usuario, quiero escribir una reseña de los servicios contratados para compartir mi experiencia con otros usuarios y proporcionar retroalimentación al proveedor.

### ISSUE THREAD

**Issue by MartinLFD** [joaonunez/proyecto-final-front-end-pt-50#24]
Historia de usuario:
- Como usuario, quiero escribir una reseña de los servicios contratados para compartir mi experiencia con otros usuarios y proporcionar retroalimentación al proveedor.

Criterio de aceptación:
- Acceso al Formulario de Reseña, Contenido del Formulario de Reseña.

**Comment by JoseB852** [comment]
revisar criterios

**Comment by MartinLFD** [comment]
Cambio realizado.
